pipeline:
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ecs
        identifier: ecs
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: vamsi_ecs
            serviceDefinition:
              spec:
                variables:
                  - name: serviceName
                    type: String
                    value: ecs-vamsi
                  - name: desiredCount
                    type: Number
                    value: 1
                  - name: taskName
                    type: String
                    value: task-vamsi
                manifests:
                  - manifest:
                      identifier: taskDef
                      type: EcsTaskDefinition
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: allutestrepogithub
                            gitFetchType: Branch
                            paths:
                              - ECS/sample/RegisterTaskDefinitionRequest.yaml
                            branch: main
                  - manifest:
                      identifier: serviceDef
                      type: EcsServiceDefinition
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: allutestrepogithub
                            gitFetchType: Branch
                            paths:
                              - ECS/sample/CreateServiceRequest.yaml
                            branch: main
                  - manifest:
                      identifier: Scaling
                      type: EcsScalingPolicyDefinition
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: allutestrepogithub
                            gitFetchType: Branch
                            paths:
                              - ECS/sample/PutScalingPolicyRequest.yaml
                            branch: main
                  - manifest:
                      identifier: Scalable
                      type: EcsScalableTargetDefinition
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: allutestrepogithub
                            gitFetchType: Branch
                            paths:
                              - ECS/sample/RegisterScalableTargetRequest.yaml
                            branch: main
                artifacts:
                  primary:
                    spec:
                      connectorRef: harnessdocker
                      imagePath: harness/todolist-sample
                      tag: "3"
                    type: DockerRegistry
              type: ECS
          infrastructure:
            environmentRef: ecs_env_vamsi
            infrastructureDefinition:
              type: ECS
              spec:
                connectorRef: awscdplayvamsi
                region: us-east-1
                cluster: ecs-tutorial
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  name: Rolling Deployment
                  identifier: rollingDeployment
                  type: EcsRollingDeploy
                  timeout: 10m
                  spec: {}
            rollbackSteps:
              - step:
                  name: Rollback Rolling Deployment
                  identifier: rollbackRollingDeployment
                  type: EcsRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: stage override
        identifier: stage_override
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            useFromStage:
              stage: ecs
            stageOverrides:
              artifacts:
                sidecars: []
                primary:
                  spec:
                    connectorRef: awscdplayvamsi
                    imagePath: test-docker
                    tag: foo
                    region: us-east-1
                  type: Ecr
              manifests:
                - manifest:
                    identifier: task2
                    type: EcsTaskDefinition
                    spec:
                      store:
                        type: Github
                        spec:
                          connectorRef: allugitHub
                          gitFetchType: Branch
                          paths:
                            - ECS/sample/RegisterTaskDefinitionRequest.yaml
                          repoName: test
                          branch: main
                - manifest:
                    identifier: service2
                    type: EcsServiceDefinition
                    spec:
                      store:
                        type: Github
                        spec:
                          connectorRef: allugitHub
                          gitFetchType: Branch
                          paths:
                            - ECS/sample/CreateServiceRequest.yaml
                          repoName: test
                          branch: main
                - manifest:
                    identifier: scaling2
                    type: EcsScalingPolicyDefinition
                    spec:
                      store:
                        type: Github
                        spec:
                          connectorRef: allugitHub
                          gitFetchType: Branch
                          paths:
                            - ECS/JsonSidecar/PutScalingPolicyRequest.json
                          repoName: test
                          branch: main
                - manifest:
                    identifier: scalable
                    type: EcsScalableTargetDefinition
                    spec:
                      store:
                        type: Github
                        spec:
                          connectorRef: allugitHub
                          gitFetchType: Branch
                          paths:
                            - ECS/JsonSidecar/RegisterScalableTargetRequest.json
                          repoName: test
                          branch: main
              variables:
                - name: serviceName
                  type: String
                  value: ecs-overr
                - name: desiredCount
                  type: Number
                  value: 1
                - name: taskName
                  type: String
                  value: task-overr
          infrastructure:
            environmentRef: ecs_env_vamsi
            infrastructureDefinition:
              type: ECS
              spec:
                connectorRef: awscdplayvamsi
                region: us-east-1
                cluster: ECSFargate
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  name: Rolling Deployment
                  identifier: rollingDeployment
                  type: EcsRollingDeploy
                  timeout: 10m
                  spec: {}
            rollbackSteps:
              - step:
                  name: Rollback Rolling Deployment
                  identifier: rollbackRollingDeployment
                  type: EcsRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: ECS_tests
  name: ECS_Stage_Override
