pipeline:
  name: ECS_Template_Tests
  identifier: ECS_Template_Tests
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: ecsdockertempstage
          versionLabel: "1"
