service: servrles182

provider:
  name: aws
  runtime: nodejs14.x
  
package:
  artifact: <+artifact.path>  

functions:
  function1:
    handler: index.handler
    
plugins:
  - serverless-domain-manager
  - serverless-plugin-log-subscription
  - serverless-pseudo-parameters
  - serverless-mocha-plugin
