service: servrles182

provider:
  name: aws
  runtime: nodejs14.x

package:
  artifact: <+artifact.path>

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
