pipeline:
    projectIdentifier: CD_Docs1
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stage1
              identifier: stage1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: K8_service
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: k8ngnix
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: k8GithubWebsite
                                                    gitFetchType: Branch
                                                    paths:
                                                        - content/en/examples/application/nginx-app.yaml
                                                    branch: main
                                            skipResourceVersioning: false
                          type: Kubernetes
                  infrastructure:
                      environmentRef: K8Env
                      infrastructureDefinition:
                          type: KubernetesGcp
                          spec:
                              connectorRef: GCPK8
                              cluster: us-central1-c/qa-target-latest
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                          provisioner:
                              steps:
                                  - step:
                                        type: CreateStack
                                        name: Create EC2 Instance
                                        identifier: Create_EC2_Instance
                                        spec:
                                            provisionerIdentifier: idd
                                            configuration:
                                                stackName: vamsi-stack
                                                connectorRef: AWS_Serverless
                                                region: us-east-1
                                                templateFile:
                                                    type: Remote
                                                    spec:
                                                        store:
                                                            type: Github
                                                            spec:
                                                                paths:
                                                                    - CF_template.yaml
                                                                connectorRef: alluHarRepoUserConn
                                                                repoName: test
                                                                gitFetchType: Branch
                                                                branch: main
                                        timeout: 10m
                                  - step:
                                        type: JiraApproval
                                        name: App
                                        identifier: App
                                        spec:
                                            connectorRef: Jira_Conn
                                            projectKey: CDS
                                            issueType: Story
                                            issueKey: CDS-41037
                                            approvalCriteria:
                                                type: KeyValues
                                                spec:
                                                    matchAnyCondition: false
                                                    conditions:
                                                        - key: FF Added
                                                          operator: equals
                                                          value: "No"
                                            rejectionCriteria:
                                                type: KeyValues
                                                spec:
                                                    matchAnyCondition: true
                                                    conditions: []
                                        timeout: 1d
                              rollbackSteps:
                                  - step:
                                        type: RollbackStack
                                        name: CF Rollback
                                        identifier: CF_Rollback
                                        spec:
                                            configuration:
                                                provisionerIdentifier: idd
                                        timeout: 10m
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    identifier: k8CloudFormation
    name: k8CloudFormation
